[package]
name = "spawn_process"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = [ "macros", "process" ] }
actix-web = "3.3"
actix-http = "2.2"
