import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { gql } from "@apollo/client"
import client from "../apollo-client"

export default function Home({countries}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {countries.map((country) => (
              <div key={country.code} className={styles.card}>
                <h3>{country.name}</h3>
                <p>
                  {country.code} - {country.emoji}
                </p>
              </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export async function getServerSideProps() {
    const { data } = await client.query({
        query: gql`
      query Countries {
        countries {
          code
          name
          emoji
        }
      }
    `,
    });

    return {
        props: {
            countries: data.countries.slice(0, 4),
        },
    };
}